# Generated by Django 3.2.4 on 2021-07-28 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, default=' Please provide a description ')),
                ('details', models.FileField(blank=True, max_length=255, null=True, upload_to='post/details', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('tag', models.TextField(blank=True, default='open to all')),
                ('is_active', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='default/project.png', upload_to='avatars')),
                ('slug', models.SlugField(max_length=250)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, max_length=255, null=True, upload_to=posts.models.cv_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('accepted', models.SmallIntegerField(choices=[(0, 'Applied'), (-1, 'Rejected'), (1, 'Accepted')], default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
