# Generated by Django 3.2.4 on 2021-07-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usr_val', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, default=' Will help your carrer')),
                ('image_url', models.URLField(blank=True)),
                ('tag', models.TextField(blank=True, default='open to all')),
                ('student', models.ManyToManyField(blank=True, to='usr_val.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr_val.teacher')),
            ],
        ),
    ]
