# Generated by Django 3.2.3 on 2021-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, default='hello')),
                ('image_url', models.URLField(blank=True)),
                ('tag', models.TextField(blank=True, default='hint')),
            ],
        ),
    ]
