# Generated by Django 3.2.4 on 2021-07-31 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('usr_val', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr_val.student'),
        ),
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='applied_students', to='usr_val.Student'),
        ),
        migrations.AddField(
            model_name='post',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr_val.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='sop',
            unique_together={('student', 'post')},
        ),
    ]
