# Generated by Django 3.2.4 on 2021-07-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210727_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(default='default/project.png', upload_to='avatars'),
        ),
    ]
