# Generated by Django 3.2.5 on 2021-12-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='backgroundKnowledge',
            field=models.TextField(blank=True, default=' Please provide a description '),
        ),
        migrations.AddField(
            model_name='post',
            name='requirements',
            field=models.TextField(blank=True, default=' Please provide a requirement'),
        ),
    ]
