# Generated by Django 3.2.3 on 2021-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0003_student'),
        ('posts', '0002_post_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.ManyToManyField(blank=True, to='usr_val.Student'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default=' Will help your carrer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.TextField(blank=True, default='open to all'),
        ),
    ]
