# Generated by Django 3.2.4 on 2021-07-26 21:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0009_auto_20210727_0313'),
        ('posts', '0004_auto_20210727_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(max_length=255, null=True, upload_to=posts.models.cv_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr_val.student')),
            ],
        ),
    ]
