# Generated by Django 3.2.4 on 2021-07-27 09:03

import django.core.validators
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_sop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='post/details', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='sop',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=posts.models.cv_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
