# Generated by Django 3.2.4 on 2021-07-15 16:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usr_val.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('BT', 'BIOTECHNOLOGY'), ('CE', 'CIVIL ENGINEERING'), ('CH', 'CHEMICAL ENGINEERING'), ('CS', 'COMPUTER SCIENCE & ENGINEERING'), ('CY', 'CHEMISTRY'), ('EC', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('EE', 'ELECTRICAL ENGINEERING'), ('ES', 'EARTH & ENVIRONMENTAL STUDIES'), ('HS', 'HUMANITIES AND SOCIAL SCIENCES'), ('MA', 'MATHEMATICS'), ('ME', 'MECHANICAL ENGINEERING'), ('MM', 'META'), ('MS', 'MANAGEMENT'), ('PH', 'PHY')], max_length=3)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('BT', 'BIOTECHNOLOGY'), ('CE', 'CIVIL ENGINEERING'), ('CH', 'CHEMICAL ENGINEERING'), ('CS', 'COMPUTER SCIENCE & ENGINEERING'), ('CY', 'CHEMISTRY'), ('EC', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('EE', 'ELECTRICAL ENGINEERING'), ('ES', 'EARTH & ENVIRONMENTAL STUDIES'), ('HS', 'HUMANITIES AND SOCIAL SCIENCES'), ('MA', 'MATHEMATICS'), ('ME', 'MECHANICAL ENGINEERING'), ('MM', 'META'), ('MS', 'MANAGEMENT'), ('PH', 'PHY')], max_length=3)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('cv', models.FileField(null=True, upload_to=usr_val.models.cv_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
