# Generated by Django 3.2.4 on 2021-07-31 13:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import usr_val.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default/einstein.jpg', upload_to='avatars')),
                ('branch', models.CharField(blank=True, choices=[('BT', 'BT'), ('CE', 'CE'), ('CH', 'CH'), ('CS', 'CH'), ('CY', 'CY'), ('EC', 'EC'), ('EE', 'EE'), ('ES', 'ES'), ('HS', 'HS'), ('MA', 'MA'), ('ME', 'ME'), ('MM', 'MM'), ('MS', 'MS'), ('PH', 'PH')], max_length=4)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default/einstein.jpg', upload_to='avatars')),
                ('branch', models.CharField(blank=True, choices=[('BT', 'BT'), ('CE', 'CE'), ('CH', 'CH'), ('CS', 'CH'), ('CY', 'CY'), ('EC', 'EC'), ('EE', 'EE'), ('ES', 'ES'), ('HS', 'HS'), ('MA', 'MA'), ('ME', 'ME'), ('MM', 'MM'), ('MS', 'MS'), ('PH', 'PH')], max_length=4)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('cgpa', models.FloatField(default=0.0)),
                ('cv', models.FileField(blank=True, max_length=255, null=True, upload_to=usr_val.models.cv_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('curr_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_project', to='posts.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ResearchStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_statement', models.TextField(default=' Please write what inspires you to do Research ', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr_val.student')),
            ],
        ),
    ]
