# Generated by Django 3.2.4 on 2021-07-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('BT', 'BT'), ('CE', 'CE'), ('CH', 'CH'), ('CS', 'CH'), ('CY', 'CY'), ('EC', 'EC'), ('EE', 'EE'), ('ES', 'ES'), ('HS', 'HS'), ('MA', 'MA'), ('ME', 'ME'), ('MM', 'MM'), ('MS', 'MS'), ('PH', 'PH')], max_length=4),
        ),
    ]
