# Generated by Django 3.2.4 on 2021-07-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0002_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
