# Generated by Django 3.2.5 on 2021-12-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0002_auto_20210805_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchstatement',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='researchstatement',
            name='research_statement',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='researchstatement',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rs', to='usr_val.student'),
        ),
    ]
