# Generated by Django 3.2.4 on 2021-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0003_alter_student_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sop',
            field=models.TextField(default=' Please write what inspires you. ', max_length=1000),
        ),
    ]
