# Generated by Django 3.2.4 on 2021-07-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0004_student_sop'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='dp',
            field=models.FileField(blank=True, upload_to='students/dp'),
        ),
    ]
