# Generated by Django 3.2.4 on 2021-07-26 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0005_auto_20210726_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='student',
            name='dp',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='students/dp', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
