# Generated by Django 3.2.4 on 2021-07-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0006_auto_20210716_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.BigIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
