# Generated by Django 3.2.4 on 2021-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0007_auto_20210716_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
