# Generated by Django 3.2.4 on 2021-07-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0007_alter_student_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dp',
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='default/einstein.jpg', upload_to='avatars'),
        ),
    ]
