# Generated by Django 3.2.4 on 2021-07-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_val', '0008_auto_20210727_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sop',
        ),
        migrations.AddField(
            model_name='student',
            name='research_statement',
            field=models.TextField(default=' Please write what inspires you. ', max_length=1000),
        ),
    ]
