# Departments
DEPARTMENTS=[
    ('BT','BIOTECHNOLOGY'),
    ('CE','CIVIL ENGINEERING'),
    ('CH','CHEMICAL ENGINEERING'),
    ('CS','COMPUTER SCIENCE & ENGINEERING'),
    ('CY','CHEMISTRY'),
    ('EC','ELECTRONICS AND COMMUNICATION ENGINEERING'),
    ('EE','ELECTRICAL ENGINEERING'),
    ('ES','EARTH & ENVIRONMENTAL STUDIES'),
    ('HS','HUMANITIES AND SOCIAL SCIENCES'),
    ('MA','MATHEMATICS'),
    ('ME','MECHANICAL ENGINEERING'),
    ('MM','META'),
    ('MS','MANAGEMENT'),
    ('PH','PHY')
]
